In [1]:
import numpy as np
import pandas as pd

import matplotlib as mpl

df = pd.read_csv("data/vehiculos_original.csv")

In [2]:
df

,make,model,year,displ,cylinders,trany,drive,VClass,fuelType,comb08,co2TailpipeGpm
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,17,522.764706
1,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,17,522.764706
2,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,13,683.615385
3,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,13,683.615385
4,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,16,555.437500
...,...,...,...,...,...,...,...,...,...,...,...
38431,smart,fortwo electric drive coupe,2011,NaN,NaN,Automatic (A1),Rear-Wheel Drive,Two Seaters,Electricity,87,0.000000
38432,smart,fortwo electric drive coupe,2013,NaN,NaN,Automatic (A1),Rear-Wheel Drive,Two Seaters,Electricity,107,0.000000
38433,smart,fortwo electric drive coupe,2014,NaN,NaN,Automatic (A1),Rear-Wheel Drive,Two Seaters,Electricity,107,0.000000
38434,smart,fortwo electric drive coupe,2015,NaN,NaN,Automatic (A1),Rear-Wheel Drive,Two Seaters,Electricity,107,0.000000
38435,smart,fortwo electric drive coupe,2016,NaN,NaN,Automatic (A1),Rear-Wheel Drive,Two Seaters,Electricity,107,0.000000

In [4]:
df = df.rename(columns={
    "cylinders":"cilindros",
    "trany":"transmision",
    "make":"fabricante",
    "model":"modelo",
    "displ":"desplazamiento",#volumen de desplazamiento del motor
    "drive":"traccion",
    "VClass":"clase",
    "fuelType":"combustible",
    "comb08":"consumo",
    "co2TailpipeGpm":"c02"
})
df.head()

,fabricante,modelo,year,desplazamiento,cilindros,transmision,traccion,clase,combustible,consumo,c02
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,17,522.764706
1,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,17,522.764706
2,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,13,683.615385
3,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,13,683.615385
4,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,16,555.437500

In [5]:
df.dtypes

fabricante         object
modelo             object
year                int64
desplazamiento    float64
cilindros         float64
transmision        object
traccion           object
clase              object
combustible        object
consumo             int64
c02               float64
dtype: object

In [6]:
df.to_csv("data/vehiculos_procesadores.csv", index=False)