In [1]:
import pandas as pd

In [2]:
pd.__version__

'1.1.5'

In [3]:
rick_morty = pd.DataFrame(
    {
        "nombre": ["Rick", "Morty"],
        "apellido": ["Sanchez", "Smith"],
        "edad": [60, 14]
    }
)
rick_morty

  nombre apellido  edad
0   Rick  Sanchez    60
1  Morty    Smith    14

In [4]:
rick_morty = pd.DataFrame(
    [
        ["Rick", "Sanchez", 60],
        ["Morty", "Smith", 14]
    ], columns=["nombre", "apellido", "edad"]
)
rick_morty

  nombre apellido  edad
0   Rick  Sanchez    60
1  Morty    Smith    14

In [5]:
type(rick_morty)

pandas.core.frame.DataFrame

In [6]:
votos = pd.read_csv("primary_results.csv")
votos

,state,state_abbreviation,county,fips,party,candidate,votes,fraction_votes
0,Alabama,AL,Autauga,1001.0,Democrat,Bernie Sanders,544,0.182
1,Alabama,AL,Autauga,1001.0,Democrat,Hillary Clinton,2387,0.800
2,Alabama,AL,Baldwin,1003.0,Democrat,Bernie Sanders,2694,0.329
3,Alabama,AL,Baldwin,1003.0,Democrat,Hillary Clinton,5290,0.647
4,Alabama,AL,Barbour,1005.0,Democrat,Bernie Sanders,222,0.078
...,...,...,...,...,...,...,...,...
24606,Wyoming,WY,Teton-Sublette,95600028.0,Republican,Ted Cruz,0,0.000
24607,Wyoming,WY,Uinta-Lincoln,95600027.0,Republican,Donald Trump,0,0.000
24608,Wyoming,WY,Uinta-Lincoln,95600027.0,Republican,John Kasich,0,0.000
24609,Wyoming,WY,Uinta-Lincoln,95600027.0,Republican,Marco Rubio,0,0.000
24610,Wyoming,WY,Uinta-Lincoln,95600027.0,Republican,Ted Cruz,53,1.000

In [12]:
df = votos

In [13]:
df.head(3)

,state,state_abbreviation,county,fips,party,candidate,votes,fraction_votes
0,Alabama,AL,Autauga,1001.0,Democrat,Bernie Sanders,544,0.182
1,Alabama,AL,Autauga,1001.0,Democrat,Hillary Clinton,2387,0.800
2,Alabama,AL,Baldwin,1003.0,Democrat,Bernie Sanders,2694,0.329

In [14]:
df.tail(5)

,state,state_abbreviation,county,fips,party,candidate,votes,fraction_votes
24606,Wyoming,WY,Teton-Sublette,95600028.0,Republican,Ted Cruz,0,0.0
24607,Wyoming,WY,Uinta-Lincoln,95600027.0,Republican,Donald Trump,0,0.0
24608,Wyoming,WY,Uinta-Lincoln,95600027.0,Republican,John Kasich,0,0.0
24609,Wyoming,WY,Uinta-Lincoln,95600027.0,Republican,Marco Rubio,0,0.0
24610,Wyoming,WY,Uinta-Lincoln,95600027.0,Republican,Ted Cruz,53,1.0

In [15]:
df.dtypes

state                  object
state_abbreviation     object
county                 object
fips                  float64
party                  object
candidate              object
votes                   int64
fraction_votes        float64
dtype: object

In [16]:
df.describe

<bound method NDFrame.describe of          state state_abbreviation          county        fips       party  \
0      Alabama                 AL         Autauga      1001.0    Democrat
1      Alabama                 AL         Autauga      1001.0    Democrat
2      Alabama                 AL         Baldwin      1003.0    Democrat
3      Alabama                 AL         Baldwin      1003.0    Democrat
4      Alabama                 AL         Barbour      1005.0    Democrat
...        ...                ...             ...         ...         ...
24606  Wyoming                 WY  Teton-Sublette  95600028.0  Republican
24607  Wyoming                 WY   Uinta-Lincoln  95600027.0  Republican
24608  Wyoming                 WY   Uinta-Lincoln  95600027.0  Republican
24609  Wyoming                 WY   Uinta-Lincoln  95600027.0  Republican
24610  Wyoming                 WY   Uinta-Lincoln  95600027.0  Republican

             candidate  votes  fraction_votes
0       Bernie Sanders    544           0.182
1      Hillary Clinton   2387           0.800
2       Bernie Sanders   2694           0.329
3      Hillary Clinton   5290           0.647
4       Bernie Sanders    222           0.078
...                ...    ...             ...
24606         Ted Cruz      0           0.000
24607     Donald Trump      0           0.000
24608      John Kasich      0           0.000
24609      Marco Rubio      0           0.000
24610         Ted Cruz     53           1.000

[24611 rows x 8 columns]>

In [17]:
df.describe()

               fips          votes  fraction_votes
count  2.451100e+04   24611.000000    24611.000000
mean   2.667152e+07    2306.252773        0.304524
std    4.200978e+07    9861.183572        0.231401
min    1.001000e+03       0.000000        0.000000
25%    2.109100e+04      68.000000        0.094000
50%    4.208100e+04     358.000000        0.273000
75%    9.090012e+07    1375.000000        0.479000
max    9.560004e+07  590502.000000        1.000000

In [18]:
df.index

RangeIndex(start=0, stop=24611, step=1)

In [19]:
df.loc[1]

state                         Alabama
state_abbreviation                 AL
county                        Autauga
fips                             1001
party                        Democrat
candidate             Hillary Clinton
votes                            2387
fraction_votes                    0.8
Name: 1, dtype: object

In [21]:
df2 = df.set_index("county")

In [23]:
df2.loc["Los Angeles"]

,state,state_abbreviation,fips,party,candidate,votes,fraction_votes
county,,,,,,,
Los Angeles,California,CA,6037.0,Democrat,Bernie Sanders,434656,0.420
Los Angeles,California,CA,6037.0,Democrat,Hillary Clinton,590502,0.570
Los Angeles,California,CA,6037.0,Republican,Donald Trump,179130,0.698
Los Angeles,California,CA,6037.0,Republican,John Kasich,33559,0.131
Los Angeles,California,CA,6037.0,Republican,Ted Cruz,30775,0.120

In [24]:
df2.iloc[1]

state                         Alabama
state_abbreviation                 AL
fips                             1001
party                        Democrat
candidate             Hillary Clinton
votes                            2387
fraction_votes                    0.8
Name: Autauga, dtype: object

In [25]:
df["state"]

0        Alabama
1        Alabama
2        Alabama
3        Alabama
4        Alabama
          ...
24606    Wyoming
24607    Wyoming
24608    Wyoming
24609    Wyoming
24610    Wyoming
Name: state, Length: 24611, dtype: object

In [26]:
df.state

0        Alabama
1        Alabama
2        Alabama
3        Alabama
4        Alabama
          ...
24606    Wyoming
24607    Wyoming
24608    Wyoming
24609    Wyoming
24610    Wyoming
Name: state, Length: 24611, dtype: object

In [27]:
df["shape"] = 1

In [28]:
df.head()

,state,state_abbreviation,county,fips,party,candidate,votes,fraction_votes,shape
0,Alabama,AL,Autauga,1001.0,Democrat,Bernie Sanders,544,0.182,1
1,Alabama,AL,Autauga,1001.0,Democrat,Hillary Clinton,2387,0.800,1
2,Alabama,AL,Baldwin,1003.0,Democrat,Bernie Sanders,2694,0.329,1
3,Alabama,AL,Baldwin,1003.0,Democrat,Hillary Clinton,5290,0.647,1
4,Alabama,AL,Barbour,1005.0,Democrat,Bernie Sanders,222,0.078,1

In [29]:
df.shape

(24611, 9)

In [31]:
df["shape"]

0        1
1        1
2        1
3        1
4        1
        ..
24606    1
24607    1
24608    1
24609    1
24610    1
Name: shape, Length: 24611, dtype: int64

In [33]:
type(df.state)

pandas.core.series.Series

In [35]:
type(df[["state","county"]])

pandas.core.frame.DataFrame

In [46]:
df[df.votes>=300000]

,state,state_abbreviation,county,fips,party,candidate,votes,fraction_votes,shape
1385,California,CA,Los Angeles,6037.0,Democrat,Bernie Sanders,434656,0.420,1
1386,California,CA,Los Angeles,6037.0,Democrat,Hillary Clinton,590502,0.570,1
4450,Illinois,IL,Chicago,91700103.0,Democrat,Bernie Sanders,311225,0.454,1
4451,Illinois,IL,Chicago,91700103.0,Democrat,Hillary Clinton,366954,0.536,1

In [37]:
df[(df.county=="Manhattan")&(df.party=="Democrat")]

,state,state_abbreviation,county,fips,party,candidate,votes,fraction_votes,shape
15011,New York,NY,Manhattan,36061.0,Democrat,Bernie Sanders,90227,0.337,1
15012,New York,NY,Manhattan,36061.0,Democrat,Hillary Clinton,177496,0.663,1

In [38]:
county = "Manhattan"
df.query("county==@county and party == 'Democrat'")

,state,state_abbreviation,county,fips,party,candidate,votes,fraction_votes,shape
15011,New York,NY,Manhattan,36061.0,Democrat,Bernie Sanders,90227,0.337,1
15012,New York,NY,Manhattan,36061.0,Democrat,Hillary Clinton,177496,0.663,1

In [39]:
df.head()

,state,state_abbreviation,county,fips,party,candidate,votes,fraction_votes,shape
0,Alabama,AL,Autauga,1001.0,Democrat,Bernie Sanders,544,0.182,1
1,Alabama,AL,Autauga,1001.0,Democrat,Hillary Clinton,2387,0.800,1
2,Alabama,AL,Baldwin,1003.0,Democrat,Bernie Sanders,2694,0.329,1
3,Alabama,AL,Baldwin,1003.0,Democrat,Hillary Clinton,5290,0.647,1
4,Alabama,AL,Barbour,1005.0,Democrat,Bernie Sanders,222,0.078,1

In [40]:
df.sort_values(by="votes", ascending=False)

,state,state_abbreviation,county,fips,party,candidate,votes,fraction_votes,shape
1386,California,CA,Los Angeles,6037.0,Democrat,Hillary Clinton,590502,0.570,1
1385,California,CA,Los Angeles,6037.0,Democrat,Bernie Sanders,434656,0.420,1
4451,Illinois,IL,Chicago,91700103.0,Democrat,Hillary Clinton,366954,0.536,1
4450,Illinois,IL,Chicago,91700103.0,Democrat,Bernie Sanders,311225,0.454,1
4463,Illinois,IL,Cook Suburbs,91700104.0,Democrat,Hillary Clinton,249217,0.536,1
...,...,...,...,...,...,...,...,...,...
8476,Maine,ME,Greenbush,92300181.0,Democrat,Hillary Clinton,0,0.000,1
8474,Maine,ME,Great Pond,92300180.0,Democrat,Hillary Clinton,0,0.000,1
8473,Maine,ME,Great Pond,92300180.0,Democrat,Bernie Sanders,0,0.000,1
9637,Massachusetts,MA,Holland,92500135.0,Democrat,No Preference,0,0.000,1
8290,Maine,ME,Castle Hill,92300087.0,Democrat,Hillary Clinton,0,0.000,1

In [44]:
df.groupby(["state","party"]).votes.sum()

state          party
Alabama        Democrat       386327
               Republican     837632
Alaska         Democrat          539
               Republican      21930
Arizona        Democrat       399097
                              ...
West Virginia  Republican     188138
Wisconsin      Democrat      1000703
               Republican    1072699
Wyoming        Democrat          280
               Republican        903
Name: votes, Length: 95, dtype: int64

In [51]:
df["Letra Estado"]= df.state_abbreviation.apply(lambda s: s[0])

In [53]:
df

,state,state_abbreviation,county,fips,party,candidate,votes,fraction_votes,shape,Letra Estado
0,Alabama,AL,Autauga,1001.0,Democrat,Bernie Sanders,544,0.182,1,A
1,Alabama,AL,Autauga,1001.0,Democrat,Hillary Clinton,2387,0.800,1,A
2,Alabama,AL,Baldwin,1003.0,Democrat,Bernie Sanders,2694,0.329,1,A
3,Alabama,AL,Baldwin,1003.0,Democrat,Hillary Clinton,5290,0.647,1,A
4,Alabama,AL,Barbour,1005.0,Democrat,Bernie Sanders,222,0.078,1,A
...,...,...,...,...,...,...,...,...,...,...
24606,Wyoming,WY,Teton-Sublette,95600028.0,Republican,Ted Cruz,0,0.000,1,W
24607,Wyoming,WY,Uinta-Lincoln,95600027.0,Republican,Donald Trump,0,0.000,1,W
24608,Wyoming,WY,Uinta-Lincoln,95600027.0,Republican,John Kasich,0,0.000,1,W
24609,Wyoming,WY,Uinta-Lincoln,95600027.0,Republican,Marco Rubio,0,0.000,1,W
24610,Wyoming,WY,Uinta-Lincoln,95600027.0,Republican,Ted Cruz,53,1.000,1,W

In [54]:
df_pobreza = pd.read_csv("PovertyEstimates.csv")

In [55]:
df_pobreza.head()

   FIPStxt  PCTPOVALL_2015
0        0            14.7
1     1000            18.5
2     1001            12.7
3     1003            12.9
4     1005            32.0

In [56]:
df_merged = df.merge(df_pobreza, left_on="fips", right_on="FIPStxt")

In [57]:
df_merged.head()

,state,state_abbreviation,county,fips,party,candidate,votes,fraction_votes,shape,Letra Estado,FIPStxt,PCTPOVALL_2015
0,Alabama,AL,Autauga,1001.0,Democrat,Bernie Sanders,544,0.182,1,A,1001,12.7
1,Alabama,AL,Autauga,1001.0,Democrat,Hillary Clinton,2387,0.800,1,A,1001,12.7
2,Alabama,AL,Autauga,1001.0,Republican,Ben Carson,1764,0.146,1,A,1001,12.7
3,Alabama,AL,Autauga,1001.0,Republican,Donald Trump,5387,0.445,1,A,1001,12.7
4,Alabama,AL,Autauga,1001.0,Republican,John Kasich,421,0.035,1,A,1001,12.7

In [58]:
df_merged.tail()

,state,state_abbreviation,county,fips,party,candidate,votes,fraction_votes,shape,Letra Estado,FIPStxt,PCTPOVALL_2015
17469,Wyoming,WY,Uinta,56041.0,Democrat,Hillary Clinton,4,0.444,1,W,56041,9.8
17470,Wyoming,WY,Washakie,56043.0,Democrat,Bernie Sanders,1,0.333,1,W,56043,11.2
17471,Wyoming,WY,Washakie,56043.0,Democrat,Hillary Clinton,2,0.667,1,W,56043,11.2
17472,Wyoming,WY,Weston,56045.0,Democrat,Bernie Sanders,1,0.500,1,W,56045,9.8
17473,Wyoming,WY,Weston,56045.0,Democrat,Hillary Clinton,1,0.500,1,W,56045,9.8

In [60]:
import xlwt

ModuleNotFoundError: No module named 'xlwt'